reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'

urlpatterns = [
    path('', views.ReportListView.as_view(), name='list'),
    path('save/', views.create_report, name='save'),
    path('<int:pk>/', views.ReportDetailView.as_view(), name='detail'),
    path('<int:pk>/pdf/', views.generate_pdf_view, name='pdf'),
    path('from-file/', views.UploadTemplateView.as_view(), name='from-file'),
    path('upload/', views.csv_upload, name='upload'),
]

reports_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from reports_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('sales/', views.SaleListView.as_view(), name='sales'),
    path('sale-detail/<int:pk>', views.SaleDetailView.as_view(), name='detail')
]

reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse

class Report(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True)
    remark = models.TextField()
    image = models.ImageField(upload_to='reports/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "Report for: " + self.author.user.username + ' --- ' + self.name

    class Meta:
        ordering = ['-created']

reports/forms.py
from django import forms
from reports.models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remark')

reports/views.py
import csv
from django.utils.dateparse import parse_date
from django.shortcuts import get_object_or_404
from reports.forms import ReportForm
from django.http import JsonResponse
from reports.utils import get_rep_image_path
from profiles.models import Profile
from reports.models import Report
from sales.models import Sale, Position, CSV
from products.models import Product
from customers.models import Customer
from django.views.generic import ListView, DetailView, TemplateView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Generating pdf libraries and imports
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = "reports/main.html"
    context_object_name = 'reports'

class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = "reports/detail.html"
    context_object_name = 'report'


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'

@login_required
def csv_upload(request):
    
    if request.method == 'POST':
        file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        csv_obj, created = CSV.objects.get_or_create(file_name=file_name)

        if created:
            csv_obj.csv_file = csv_file
            csv_obj.save()

            with open(csv_obj.csv_file.path, 'r') as f:
                reader = csv.reader(f)
                reader.__next__()

                for row in reader:
                    transaction_id = row[1]
                    product = row[2]
                    quantity = int(row[3])
                    customer = row[4]
                    date = parse_date(row[5])

                    #Find product
                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(
                            product=product_obj,
                            quantity=quantity,
                            created=date
                        )

                        sale_obj, _ = Sale.objects.get_or_create(
                            transaction_id=transaction_id,
                            customer=customer_obj,
                            salesman=salesman_obj,
                            created=date
                        )
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({'exist': False})
        else:
            return JsonResponse({'exist': True})
    return JsonResponse({})

@login_required
def create_report(request):
    if request.is_ajax():
        img = request.POST.get('image')
        image = get_rep_image_path(img)
        form = ReportForm(request.POST)
        if form.is_valid():
            profile = Profile.objects.get(user=request.user)
            instance = form.save(commit=False)
            instance.image = image
            instance.author = profile
            instance.save()
            return JsonResponse({'msg': 'Report Save!'})

    return JsonResponse({})

@login_required
def generate_pdf_view(request, pk):

    report = get_object_or_404(Report, pk=pk)

    template_path = 'reports/pdf.html'
    context = {'report': report}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')

    #Direct download pdf
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'

    #Display reports content in pdf file
    response['Content-Disposition'] = 'filename="report.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

reports/templates/reports/detail.html
{% extends "base.html" %}
{% block title %}
| {{report.name}}
{% endblock title %}

{% block content %}
<div class="card">
    {% if report.image %}
    <img src="{{report.image.url}}" style="width: 70%; height: 500px" class="card-img-top" alt="{{report.name}}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{report.name}}</h5>
        <p class="card-text">{{report.remark}}</p>
        <p class="card-text">Created by: {{report.author.user.username}}</p>
        <p class="card-text">Created at: {{report.created}}</p>
        <hr>
        <a href="{% url 'reports:list' %}" class="btn btn-outline-info">Reports List</a>
        <a href="{% url 'reports:pdf' report.pk %}" class="btn btn-outline-danger">PDF</a>
    </div>
</div>
{% endblock content %}

reports/templates/reports/from_file.html
{% extends "base.html" %}
{% load static %}

{% block title %}
| Upload CSV Files
{% endblock title %}

{% block style %}
<style>
    .dz-remove {
        color: red;
        text-decoration: none;
        text-transform: capitalize;
    }
</style>
{% endblock style %}

{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<h4 class='text-center'>Upload your sale files</h4>
<div id="alert-box"></div>
<br>
<form id="my-dropzone" class="dropzone dz">
    {% csrf_token %}
    <div class="fallback">
        <input type="file" name="file" id="" multiple />
    </div>
</form>
{% endblock content %}

reports/templates/reports/main.html
{% extends "base.html" %}
{% block title %}
| Reports
{% endblock title %}

{% block content %}
{% for report in reports %}
<div class="card" height='50'>
    {% if report.image %}
    <img src="{{report.image.url}}" style="width: 70%; height: 500px" class="card-img-top" alt="{{report.name}}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{report.name}}</h5>
        <p class="card-text">{{report.remark|truncatewords:1}}</p>
        <a href="{{report.get_absolute_url}}" class="btn btn-outline-info">Detail</a>
        <a href="{% url 'reports:pdf' report.pk %}" class="btn btn-outline-danger">PDF</a>
    </div>
</div>
<br>
{% endfor %}
{% endblock content %}

reports/templates/reports/pdf.html
{% extends "base.html" %}

{% block title %}
| {{report.name|title}}
{% endblock title %}

{% block style %}
<style>
    h2 {
        font-size: 18px;
        color: red;
    }

    p {
        font-size: 14px;
        letter-spacing: 1px;
        color: green;
    }
</style>
{% endblock style %}

{% block content %}

<h2 align="center">{{report.name}}</h2>

<hr color='blue' size='3'>
<img src="{{report.image.path}}" alt="{{report.name}}">

<h2>Remarks: </h2>
<p>{{report.remark}}</p>
<hr color='blue' size='3'>
<br>
<p>Author: <b>{{report.author.user.username}}</b></p>
<p>Created: <b>{{report.created}}</b></p>

{% endblock content %}