profiles/urls.py
from django.urls import path
from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('my-profile', views.my_profile, name='my-profile'),
]

reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'

urlpatterns = [
    path('', views.ReportListView.as_view(), name='list'),
    path('save/', views.create_report, name='save'),
    path('<int:pk>/', views.ReportDetailView.as_view(), name='detail'),
    path('<int:pk>/pdf/', views.generate_pdf_view, name='pdf'),
    path('from-file/', views.UploadTemplateView.as_view(), name='from-file'),
    path('upload/', views.csv_upload, name='upload'),
]

reports_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from reports_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('sales/', views.SaleListView.as_view(), name='sales'),
    path('sale-detail/<int:pk>', views.SaleDetailView.as_view(), name='detail')
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>


    <!-- Dropzone CSS and JS -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}"></script>


    <!-- Custom CSS and JS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}


    {% block style %}
    {% endblock style %}

    <title>Report App {% block title %} {% endblock title %} </title>
</head>

<body>

    {% include 'navbar.html' %}

    <div class="container mt-3 mb-3">
        {% block content%}
        {% endblock content %}
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>

</body>

</html>

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
| Login
{% endblock title %}

{% block content %}

<div class="col-sm-6 offset-3">
    <h2 class="alert alert-info text-center">Login for further process</h2>
    {% if err_msg %}
    <div class="alert alert-danger">
        {{err_msg}}
    </div>
    {% endif %}

    <form action="" method="POST" novalidate class='p-3 border border-1'>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Login" class='btn btn-outline-info mt-2'>
    </form>

</div>


{% endblock content %}

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'sales:home' %}"><img src="{% static 'logo.png' %}" class="logo-sm"></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sales:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sales:sales' %}">Sales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:from-file' %}">Add from file</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reports:list' %}">Reports</a>
                </li>
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
            <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <img src="{{request.user.profile.avatar.url}}" class="avatar-nav">&nbsp;{{request.user}}
            </div>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'profiles:my-profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>